"""add rag document source tracking

Revision ID: d1550e1f796c
Revises: 88ccbd67821c
Create Date: 2026-09-17 23:33:55.780350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1550e1f796c'
down_revision: Union[str, Sequence[str], None] = '88ccbd67821c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('chunk_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'chunk_index')
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
